apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-cip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-cip
  template:
    metadata:
      labels:
        app: my-app-cip
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
  labels: 
    name: my-app-cip
    env: test
spec:
    type: ClusterIP
    ports: 
    - port: 80
      protocol: TCP
    selector:
      name: my-app-cip
