apiVersion: apps\v1
kind: Deployment
metadata: 
  name: my-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
spec:
   containers:
   - name: nginx 
   ports:
   - containerPort: 8080