apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: my-pvc2
      mountPath: /usr/share/nginx/html
  volumes:
  - name: my-pvc2
    persistentVolumeClaim:
      claimName: my-pvc
