apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: default
  name: pod-reader
rules:
  - apiGroup: ["rbac.authorization.k8s.io/v1"]
    resource: ["pods"]
    verbs: ["get", "watch", "list"]