apiVersion: v1
kind: Pod
metadata:
  name: Annotations
  annotations:
    imageregistery: "https://hub.docker.com"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 8080