apiVersion: v1
kind: Pod
metadata:
  name: pod-config1
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course1
        valueFrom:
          configMapkeyRef:
            name: config
            key: course
      - name: duration1
        valueFrom:
          configMapkeyRef:
            name: config
            key: duration
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-config2
spec:
  containers:
  - name: nginx
    image: nginx     
    envFrom:
      - configMapRef:
         name: config     

      