apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-ebs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-ebs-sc
  #/local:
   # path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-192-168-40-228.ec2.internal
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-03946b397139cbac3
    volumeAttributes:
      persistentVolumeReclaimPolicy: Retain