apiVersion: v1
kind: pod
metadata: 
  name: limits
spec:
  containers:
  name: nginx
  image: nginx
  resource:
    requests:
      cpu: 100m
      memory: 68mi
    limit:
      cpu: 120m
      memory: 100mi