apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: dev
spec:
  containers:
  - image: redis
    name: redis
  tolerations:
  - key: "app"
    operator: "Equal"
    value: "app1"
    effect: "NoExecute"
  - key: "gpu"
    operator: "Equal"
    value: "false"
    effect: "NoSchedule"