apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: dev
spec:
  containers:
  - image: redis
    name: redis
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"